# Generated by Django 4.0.4 on 2022-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baymarket', '0002_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
