# Generated by Django 4.0.4 on 2022-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baymarket', '0007_product_not_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='not_verified_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
