# Generated by Django 4.0.4 on 2022-05-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_account_phone'),
        ('baymarket', '0008_product_moderation_product_not_verified_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baymarket_product_account', to='control.account'),
        ),
    ]
