# Generated by Django 4.0.4 on 2022-05-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baymarket', '0009_remove_product_company_product_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baymarket_product_productimage', to='baymarket.product'),
        ),
    ]
