# Generated by Django 4.0.4 on 2022-05-18 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_account_phone'),
        ('baymarket', '0011_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baymarket_product_moderator', to='control.account'),
        ),
    ]
