# Generated by Django 4.0.4 on 2022-04-22 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_rename_disctrict_district'),
        ('baycar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMarka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baycar_product_account', to='control.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='arenda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baycar_product_district', to='control.district'),
        ),
        migrations.AddField(
            model_name='product',
            name='dizel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='dollar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='drive_unit',
            field=models.CharField(blank=True, choices=[('orqa', 'orqa'), ('oldi', 'oldi'), ('orqa va oldi', 'orqa va oldi')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='electr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='fix_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='oil',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baycar_product_region', to='control.region'),
        ),
        migrations.AddField(
            model_name='product',
            name='sum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baycar.productcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baycar.productmarka'),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baycar.producttransmission'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baycar.producttype'),
        ),
    ]
