# Generated by Django 4.0.4 on 2022-04-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_room_message'),
        ('baycar', '0002_productcolor_productmarka_producttransmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baycar_wishist_account', to='control.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baycar_wishlist_product', to='baycar.product')),
            ],
        ),
    ]
