# Generated by Django 4.0.4 on 2022-05-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baycar', '0005_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
