# Generated by Django 4.0.4 on 2022-04-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_room_message'),
        ('bayhouse', '0003_condition_material_type_product_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bayhouse_wishlist_account', to='control.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bayhouse_wishlist_product', to='bayhouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='HouseConven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.BooleanField(default=False)),
                ('aircondition', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('sewer', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('furniture', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('washing', models.BooleanField(default=False)),
                ('camera', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('park', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bayhouse.product')),
            ],
            options={
                'verbose_name': 'Удобства',
                'verbose_name_plural': 'Удобствы',
            },
        ),
    ]
