# Generated by Django 4.0.4 on 2022-05-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayhouse', '0005_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arenda',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dollar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sum',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
