# Generated by Django 4.0.4 on 2022-04-22 05:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_rename_disctrict_district'),
        ('baywork', '0002_alter_message_room_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2004), django.core.validators.MinValueValidator(1950)]),
        ),
        migrations.AddField(
            model_name='product',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.district'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.region'),
        ),
    ]
