# Generated by Django 4.0.4 on 2022-04-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disctrict',
            new_name='District',
        ),
    ]
