# Generated by Django 4.0.4 on 2022-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_message_date_created_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
