# Generated by Django 4.0.4 on 2022-04-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_id',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
