# Generated by Django 4.0.4 on 2022-04-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_account_balance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mobile_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
