# Generated by Django 4.0.4 on 2022-05-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_accounttemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttemp',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
