# Generated by Django 4.0.4 on 2022-05-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_alter_accounttemp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttemp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
